### ISSUE TITLE
师傅您好 如图选择排序情况下，切换项目，程序显示问题，也会数据卡死

### ISSUE THREAD

**Issue by thelostworldFree** [Acmesec/Sylas#1]
![image](https://user-images.githubusercontent.com/24971604/148690462-d0440dac-7ab9-49d5-900c-4864648d97e1.png)
师傅您好 如图选择排序情况下，切换项目，程序显示问题，也会数据卡死

**Comment by broken5** [comment]
临时解决方案：重启burp插件，我现在正在看怎么修复。

**Comment by thelostworldFree** [comment]
> 临时解决方案：重启burp插件，我现在正在看怎么修复。

辛苦了师傅
