### ISSUE TITLE
安装插件时报错

### ISSUE THREAD

**Issue by o-zero-o** [Acmesec/Sylas#4]
![image](https://user-images.githubusercontent.com/106418239/170808381-b0875f3f-773c-4c84-bc79-16090973487c.png)

**Comment by 0Chencc** [comment]
是从https://github.com/Acmesec/Sylas/releases/tag/1.0.6 下载的包吗，看起来是自己编译的

**Comment by o-zero-o** [comment]
已经解决了，谢谢，下载错了，第一次用github
