### ISSUE TITLE
jdk8运行报错：Sylas-1.0.6.jar中没有主清单属性

### ISSUE THREAD

**Issue by flyballon** [Acmesec/Sylas#7]
![image](https://user-images.githubusercontent.com/76584208/172285556-e23a265b-d3ba-4ef8-a2ae-0fcca3d8bf63.png)

**Comment by 0Chencc** [comment]
Sylas并非是可以直接启动的jar包，而是作为BurpSuite的插件使用，需要启动Burp之后加载

**Comment by flyballon** [comment]
好的谢谢！

在 2022年6月8日星期三，林晨 ***@***.***> 写道：
